# Project: Projeto1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = mainProjeto.o funcoes.o
LINKOBJ  = mainProjeto.o funcoes.o
LIBS     = -L"D:/Programas/Devc/Dev-Cpp/MinGW64/lib" -L"D:/Programas/Devc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/Programas/Devc/Dev-Cpp/MinGW64/include" -I"D:/Programas/Devc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Programas/Devc/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Programas/Devc/Dev-Cpp/MinGW64/include" -I"D:/Programas/Devc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Programas/Devc/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Programas/Devc/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ProjetoORG.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

mainProjeto.o: mainProjeto.c
	$(CC) -c mainProjeto.c -o mainProjeto.o $(CFLAGS)

funcoes.o: funcoes.c
	$(CC) -c funcoes.c -o funcoes.o $(CFLAGS)
